//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoenterpriseApp.DataBaseFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class brigadiers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public brigadiers()
        {
            this.masters = new HashSet<masters>();
        }
    
        public int idBrigadier { get; set; }
        public string nameBrigadier { get; set; }
        public int idBrigade { get; set; }
    
        public virtual brigades brigades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<masters> masters { get; set; }
    }
}
