//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoenterpriseApp.DataBaseFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class destinations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public destinations()
        {
            this.transport = new HashSet<transport>();
        }
    
        public int idDestintaion { get; set; }
        public string departureDestination { get; set; }
        public string terminalDestination { get; set; }
        public string codeDestination { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transport> transport { get; set; }
    }
}
