//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoenterpriseApp.DataBaseFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class service
    {
        public int idService { get; set; }
        public string nameService { get; set; }
        public int idBrigade { get; set; }
    
        public virtual brigades brigades { get; set; }
    }
}
